#!/bin/bash
#
#
APACHE2=$(dpkg-query -W -f='${Status}' apache2 2>/dev/null | grep -c "ok installed") #kontrollib kas apache on olemas
if [ $APACHE2 -eq 0 ] #kui apachet ei ole siis alustab installiga
then
	echo "Alustan paketi apache2 paigaldust"
	pause
	apt install apache2 -y

elif [ $APACHE2 -eq 1 ] #kui apache on paigaldatud siis ütleb et on olemas ja näitab teenuse staatust
then
	echo "Apache2 on paigaldatud"
	pause
	systemctl status apache2
fi
